services:
  ### Posgres database for Inventory
  db-inventory:
    container_name: db-inventory
    image: postgres:15.2
    restart: unless-stopped
    environment:

      POSTGRES_DB: ms_inventory
      POSTGRES_USER: uncledave
      POSTGRES_ROOT_PASSWORD: Test123
      POSTGRES_PASSWORD: Test123
    ports:
      - "5434:5431"
    expose:
      - 5431
    command: -p 5431

  ### MySQL database for Orders
  db-orders:
    container_name: db-orders
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ms_orders
      MYSQL_USER: uncledave
      MYSQL_PASSWORD: Test123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    expose:
      - 3306

  ### Posgres database for Products
  db-products:
    container_name: db-products
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_products
      POSTGRES_USER: uncledave
      POSTGRES_ROOT_PASSWORD: Test123
      POSTGRES_PASSWORD: Test123
    ports:
      - "5433:5432"
    expose:
      - 5432
    command: -p 5432

  ### Postgres database for Keycloack
  db-keycloak:
    container_name: db-keycloak
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: Test123
    ports:
      - "5435:5432"
    expose:
      - 5432

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    command:
      - start-dev
    ports:
      - "8185:8080"
    depends_on:
      - db-keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db-keycloak:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: Test123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

  #Zookeeper
  zookeeper:
      container_name: zookeeper
      image: confluentinc/cp-zookeeper:7.4.0
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181 # Port for Zookeeper client connections
        ZOOKEEPER_TICK_TIME: 2000 # Tick time in milliseconds

      ports:
      - "2181:2181"
  #Kafka

  kafka:
      container_name: kafka
      image: confluentinc/cp-kafka:7.4.0
      depends_on:
          - zookeeper
      environment:
          KAFKA_BROKER_ID: 1 # Unique broker ID
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 # Zookeeper connection string
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT # Security protocol mapping
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29892, PLAINTEXT_HOST://localhost:9092 # Advertised listeners
          KAFKA_OFFSET_TOPIC_REPLICATION_FACTOR: 1 # Replication factor for the offsets topic
          KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1 # Replication factor for the transaction state log
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1 # Replication factor for the transaction state log
          KAFKA_LISTENERS: INSIDE://
      ports:
        - "9092:9092" # Internal Kafka port
